### ISSUE TITLE
Builders for Request are to limiting

### ISSUE THREAD

**Issue by fooker** [tekjar/rumq#22]
_First of all: I like the new design - thanks for all the work._

The builders used to create `Request`s feel to limiting for certain use-cases.
Here are some examples:
* `subscribe` allows only to pass a single topic. During mass-subscribe, I have a `Vec` of topics already. It would be nice to have a builder which allow me to pass this directly.
* `Publish` uses a `Arc<Vec<u8>>` as payload, but the builder does not allow to pass an `Arc`. I've got an `Arc` already, as I'm publishing the same message in a loop. Would be nice to avoid the `clone`s.

I'm not really sure what's the best way to design such an API. But maybe wi can use this issue to collect some ideas/use-cases.

**Comment by tekjar** [comment]
Thanks for the feedback

> * `subscribe` allows only to pass a single topic. During mass-subscribe

I'll add `add_multiple` here in the next release
```rust
pub fn empty_subscribe() -> Subscribe {
    Subscribe {
        pkid: PacketIdentifier(0),
        topics: Vec::new(),
    }
}

impl Subscribe {
    pub fn add(&mut self, topic: String, qos: QoS) -> &mut Self {
        let topic = SubscribeTopic { topic_path: topic, qos };
        self.topics.push(topic);
        self
    }
}
```

> * `Publish` uses a `Arc<Vec<u8>>` as payload, but the builder does not allow to pass an `Arc`. I've got an `Arc` already, as I'm publishing the same message in a loop. Would be nice to avoid the `clone`s

I'm not sure what we can do here as using the same message is related to ownership and `Publish` cannot be `Copy`

Also publish doesn't take `qos` in the default args. Do you think the below API args should have QoS also

```rust
pub fn publish<S: Into<String>, P: Into<Vec<u8>>>(topic: S, payload: P) -> Publish {
```

**Comment by fooker** [comment]
I didn't see `empty_subscribe`, as I was not using latest master but the alpha release. But it makes sense in combination with `add_multiple` (maybe `ad_topic` and `add_topics` are better names).

About the `Arc`: all I want to do is pass in an existing `Arc`.

Maybe the easiest way to get more flexibility is to have the fields in the types `pub`. This only works out if all combinations of values always result in valid packets (i.e.: is it valid to have a subscribe without a topic?). If we can find some most-common settings for these types, it may be feasible to implement `Default` for these types, too.

In addition, I would like to see `Into<Request>` implementations for all its implementation types.

**Comment by tekjar** [comment]
> I didn't see `empty_subscribe`, as I was not using the latest master but the alpha release. But it makes sense in combination with `add_multiple` (maybe `ad_topic` and `add_topics` are better names)

Yeah. Or `add_filter` and `add_filters`. Filter is the correct nomenclature for subscriptions I guess 

> Maybe the easiest way to get more flexibility is to have the fields in the types `pub`

I think they are already public in the master. As you mentioned, the problem would be validation. I think we can worry about it later

> In addition, I would like to see Into<Request> implementations for all its implementation types

Sure. I'll release the next cut in a few days. Pull requests with these changes would also be helpful :)

**Comment by fooker** [comment]
PR for `From`/`Into` implementations: https://github.com/tekjar/rumq/pull/25.

**Comment by tekjar** [comment]
All the core APIs have public fields now
