### ISSUE TITLE
PacketIdentifier 0

### ISSUE THREAD

**Issue by therealprof** [tekjar/rumq#33]
As per [MQTT-2.3.1-1] requirement packet identifiers MUST be non-zero. However not only can it be zero as per https://github.com/tekjar/rumq/blob/30725bee1d71de0344fc1530a4e2952a08593621/rumq-core/src/packets.rs#L7
it also defaults to 0 in a few places, e.g. in:
https://github.com/tekjar/rumq/blob/30725bee1d71de0344fc1530a4e2952a08593621/rumq-core/src/packets.rs#L147

**Comment by tekjar** [comment]
Just verified the spec. You are right. I'll fix this right away

**Comment by tekjar** [comment]
@therealprof Looks like [this method](https://github.com/tekjar/rumq/blob/30725bee1d71de0344fc1530a4e2952a08593621/rumq-client/src/state.rs#L349-L356) is handling the state correctly by returning the increment.

But I agree that this can be a source of confusion and PRs are welcome :)
