### ISSUE TITLE
Expose state somewhat

### ISSUE THREAD

**Issue by qm3ster** [tekjar/rumq#37]
In https://github.com/tekjar/rumq/blob/8c20d58523bcd5ca74c823a9f20c0f3dc5a04393/rumq-client/src/eventloop.rs#L72-L76, it is alleged that  `options`, `state` and `requests` can be accessed and even updated, at least in case of error. However, these fields of `MqttState` are private, and none of the component are returned in error variants or anything.

Maybe `fn stream` should consume the `MqttState` so that it can only by accessed when the stream isn't polled?

**Comment by tekjar** [comment]
Fixed in #42
