### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by schungx** [tekjar/rumq#38]
When using `rumq-client` (version `alpha.5`) in `Cargo.toml`, it fails to compile due to a bunch of missing functions such as `time::throttle` and in `tokio`...

Environment: Windows 10  
Toolchain: `stable-x86_64-pc-windows-msvc`

**Comment by tekjar** [comment]
Don't have a windows machine ATM. I'll try to test this sometime soon

**Comment by schungx** [comment]
It complains of functions not found (e.g. `time::throttle`) so I think it is probably a version problem...

**Comment by atonkyra** [comment]
Fails on linux too for me.
