### ISSUE TITLE
Function and method names should be more self-declaring

### ISSUE THREAD

**Issue by TotalKrill** [tekjar/rumq#41]
Example:

`rumq_client::publish` does not publish anything, it creates a Publish object that would later have to be sent to the eventstream. same with `rumq_client::subscribe`

It would make more sense to have them as `Publish::new(...)` and `Subscribe::new(..)`, or just rename them into `create_publish`, and `create_subscribe`

There are numerous such issues that should be addressed before a 1.0 release, to make it easier for newcomers to navigate the library. Lets collect those issues here and discuss them.

**Comment by tekjar** [comment]
Fixed in some commit that I don't remember :). Please feel free to reopen this if you have more issues
