### ISSUE TITLE
Build broken because of tokio::select

### ISSUE THREAD

**Issue by flxo** [tekjar/rumq#44]
I'm super confused. When pulling in `rums-client` as a dependency along with `tokio` in a otherwise completely empty project:

```
[dependencies]
tokio = "0.2"
rumq-client = { git = "https://github.com/tekjar/rumq.git" }
```

I get a strange compilation error regarding `tokio::select`.

```
~/asdf ‹master*› cargo build
    Updating git repository `https://github.com/tekjar/rumq.git`
    Updating crates.io index
   Compiling rumq-client v0.1.0-alpha.6 (https://github.com/tekjar/rumq.git#b0adb18b)
error[E0432]: unresolved import `tokio::select`
 --> /Users/felix/.cargo/git/checkouts/rumq-df81ca706f7bfd29/b0adb18/rumq-client/src/eventloop.rs:6:5
  |
6 | use tokio::select;
  |     ^^^^^^^^^^^^^ no `select` in the root

error: cannot determine resolution for the macro `select`
   --> /Users/felix/.cargo/git/checkouts/rumq-df81ca706f7bfd29/b0adb18/rumq-client/src/eventloop.rs:120:21
    |
120 |                     select! {
    |                     ^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rumq-client`.
```

 @mojzu had something similar in #34 . Pinning the `tokio` dependency to the latest `0.2.13` ends up with the same error. The toolchain ist latest stable and `rumq` builds fine when built standalone. 

I tracked down the change that causes the error to #42 which changes nothing regarding deps, versions etc... 

Any ideas?

**Comment by mojzu** [comment]
What tokio version does your Cargo.lock have? In my case the dependency resolution used tokio 0.2.6 when the Cargo.toml specified "0.2". Although setting it to "0.2.13" worked for me, my Cargo.lock now has the line "checksum tokio 0.2.13 ..." and compilation works.

**Comment by tekjar** [comment]
Oh wow! This is weird

**Comment by tekjar** [comment]
Dependency issue. Can you try this again @flxo?

**Comment by flxo** [comment]
@tekjar Thanks. 4d0dbdec0a13b8ed521b9ea80a90e67dc8cd9354 fixed.
