### ISSUE TITLE
Notification enum should not contain Connected

### ISSUE THREAD

**Issue by TotalKrill** [tekjar/rumq#50]
The Notification enum should not contain the variant Connected, since this can never happen once the stream created. It should not be mixed with the other MQTT stream logic, since It will only happen once, and only happen as the first thing when creating eventloop.

When creating the eventloop or stream this should be reported back in the form of a Result<Connected, ConnectionError> 

Example:
```rust
let mut eventstream = eventloop(mqtt_options, rx).stream();

// this will always be the first event in a successfull connection
if let Some(Notification::Connected) = eventstream.next() {
  while let Some(notif) = evenstream.next() {
    match notif {
      Notification::Connected { 
      // this can never happen again, and should thus not be part of this enum
      // and having it here kind of bloats the user logic
      },
      _ => { // all interesting events },
    }
  }
} 
```

**Comment by tekjar** [comment]
This is fixed but I might have to bring this back as high level client hides the eventloop
